
GET http://localhost:5200/games

###
GET http://localhost:5200/games/6

###
POST http://localhost:5200/games
Content-Type: application/json

{
    "name" : "RE4 Remake",
    "genreId" : 3,
    "price" : 49.99,
    "releaseDate" : "2020-12-10"
}

###
DELETE http://localhost:5200/games/2

###
PUT http://localhost:5200/games/6
Content-Type: application/json

{
    "name" : "Cyberpunk 2077 Phantom Liberty",
    "genreId" : 3,
    "price" : 70.99,
    "releaseDate" : "2020-12-10"
}