
GET http://localhost:5076/games

###
GET http://localhost:5076/games/6

###
POST http://localhost:5076/games
Content-Type: application/json

{
    "name" : "Cyberpunk 2077",
    "genre" : "Action RPG",
    "price" : 69.99,
    "releaseDate" : "2020-12-10"
}

###
DELETE http://localhost:5076/games/2

###
PUT http://localhost:5076/games/6
Content-Type: application /json

{
    "name" : "Cyberpunk 2077 Phantom Liberty",
    "genre" : "Action RPG",
    "price" : 700.99,
    "releaseDate" : "2020-12-10"
}