using GameStore.Api.Dtos;
using GameStore.Api.Models;
using Microsoft.AspNetCore.Mvc;

namespace GameStore.Api.Controllers;

/// <summary>
/// API controller for managing games.
/// Handles all CRUD operations (Create, Read, Update, Delete) for games.
/// 
/// Note: Currently uses in-memory storage. To use database persistence,
/// inject GameStoreContext and replace the static list with EF Core queries.
/// </summary>
[ApiController]
[Route("[controller]")]
public class GamesController : ControllerBase
{
    /// <summary>
    /// In-memory collection of games with sample data.
    /// 
    /// Important: GenreId must match Genre.Id to keep foreign key data consistent.
    /// This is crucial for future database migrations and queries.
    /// </summary>
    private static List<Game> games = new List<Game>
    {
        new Game { Id = 1, Name = "The Legend of Zelda: Breath of the Wild", GenreId = 1, Genre = new Genre { Id = 1, Name = "Action-adventure" }, Price = 59.99m, ReleaseDate = new DateOnly(2017, 3, 3) },
        new Game { Id = 2, Name = "Super Mario Odyssey", GenreId = 2, Genre = new Genre { Id = 2, Name = "Platformer" }, Price = 59.99m, ReleaseDate = new DateOnly(2017, 10, 27) },
        new Game { Id = 3, Name = "Red Dead Redemption 2", GenreId = 1, Genre = new Genre { Id = 1, Name = "Action-adventure" }, Price = 59.99m, ReleaseDate = new DateOnly(2018, 10, 26) },
        new Game { Id = 4, Name = "The Witcher 3: Wild Hunt", GenreId = 3, Genre = new Genre { Id = 3, Name = "Action RPG" }, Price = 39.99m, ReleaseDate = new DateOnly(2015, 5, 19) },
        new Game { Id = 5, Name = "Minecraft", GenreId = 4, Genre = new Genre { Id = 4, Name = "Sandbox" }, Price = 26.95m, ReleaseDate = new DateOnly(2011, 11, 18) }
    };

    /// <summary>
    /// Gets all games.
    /// Returns the entire collection of games in the system.
    /// </summary>
    /// <returns>200 OK with a list of GameDto objects.</returns>
    // GET /games
    [HttpGet]
    public ActionResult<List<GameDto>> GetAllGames()
    {
        // Convert Game models to GameDto for API response
        // Use Select to project each game to a DTO with only necessary fields
        var gameDtos = games.Select(game => new GameDto(
            game.Id,
            game.Name,
            game.Genre?.Name ?? string.Empty,  // Handle null genres gracefully
            game.Price,
            game.ReleaseDate
        )).ToList();

        return Ok(gameDtos);
    }

    /// <summary>
    /// Gets a game by its ID.
    /// Returns a single game if found, otherwise returns 404.
    /// </summary>
    /// <param name="id">The ID of the game to retrieve.</param>
    /// <returns>200 OK with the game, or 404 Not Found if not found.</returns>
    // GET /games/{id}
    [HttpGet("{id}")]
    public ActionResult<GameDto> GetGameById(int id)
    {
        // Find the game by ID in the in-memory list
        var game = games.FirstOrDefault(g => g.Id == id);

        // Return 404 if game does not exist
        if (game == null)
        {
            return NotFound();
        }

        // Map to DTO for response
        var gameDto = new GameDto(
            game.Id,
            game.Name,
            game.Genre?.Name ?? string.Empty,  // Handle null genres gracefully
            game.Price,
            game.ReleaseDate
        );

        return Ok(gameDto);
    }

    /// <summary>
    /// Creates a new game.
    /// 
    /// Important: IDs are generated by finding the max existing ID and adding 1.
    /// This prevents ID collisions if games are deleted from the list.
    /// </summary>
    /// <param name="newGame">The new game to create (validated via CreateGameDto).</param>
    /// <returns>201 Created with Location header and the created game data.</returns>
    // POST /games
    [HttpPost]
    public ActionResult<GameDto> CreateGame(CreateGameDto newGame)
    {
        // Generate the next available GenreId by finding the max existing GenreId + 1
        // DefaultIfEmpty() ensures we get 0 if the list is empty, preventing errors
        var nextGenreId = games
            .Select(g => g.GenreId)
            .DefaultIfEmpty()
            .Max() + 1;

        // Create a new Game with auto-assigned ID and GenreId
        // Using .Max() + 1 instead of .Count + 1 ensures unique IDs even after deletions
        var game = new Game
        {
            Id = games.Select(g => g.Id).DefaultIfEmpty().Max() + 1,
            Name = newGame.Name,
            GenreId = nextGenreId,
            Genre = new Genre { Id = nextGenreId, Name = newGame.Genre },
            Price = newGame.Price,
            ReleaseDate = newGame.ReleaseDate
        };

        games.Add(game);

        // Map to DTO for response
        var gameDto = new GameDto(
            game.Id,
            game.Name,
            game.Genre?.Name ?? string.Empty,
            game.Price,
            game.ReleaseDate
        );

        // Return 201 Created with Location header pointing to the new resource
        return CreatedAtAction(
            nameof(GetGameById),
            new { id = game.Id },
            gameDto
        );
    }

    /// <summary>
    /// Deletes a game by its ID.
    /// Finds the game in memory and removes it from the list.
    /// </summary>
    /// <param name="id">The ID of the game to delete.</param>
    /// <returns>204 No Content if successful, 404 if not found.</returns>
    // DELETE /games/{id}
    [HttpDelete("{id}")]
    public ActionResult DeleteGame(int id)
    {
        // Find the game with the given ID
        var game = games.FirstOrDefault(g => g.Id == id);

        // Return 404 if game does not exist
        if (game == null)
        {
            return NotFound();
        }

        // Remove the game from the in-memory list
        games.Remove(game);
        
        // Return 204 No Content (successful deletion with no response body)
        return NoContent();
    }

    /// <summary>
    /// Updates an existing game by its ID.
    /// Validates the request and updates the game's properties.
    /// </summary>
    /// <param name="id">The ID of the game to update.</param>
    /// <param name="updatedGame">The updated game data (validated via UpdateGameDto).</param>
    /// <returns>204 No Content if successful, 404 if not found, 400 if validation fails.</returns>
    [HttpPut("{id}")]
    public ActionResult UpdateGame(int id, UpdateGameDto updatedGame)
    {
        // Validate the request body (occurs automatically via DTO validation)
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        // Find the game with the given ID
        var game = games.FirstOrDefault(g => g.Id == id);

        // Return 404 if game does not exist
        if (game == null)
        {
            return NotFound();
        }

        // Update the game's properties from the request
        game.Name = updatedGame.Name;
        game.Genre = new Genre { Id = game.GenreId, Name = updatedGame.Genre };
        game.Price = updatedGame.Price;
        game.ReleaseDate = updatedGame.ReleaseDate;

        // Return 204 No Content (successful update with no response body)
        return NoContent();
    }
}
